import pickle
from sklearn.ensemble import RandomForestRegressor as randomforest
from sklearn.neural_network import MLPRegressor as mlp
from sklearn.linear_model import RidgeCV

def main():
  '''
  Driver function to demo loading saved models to perform regression tasks.
  Saved models and feature maps are serialized (saved) and de-serialized 
  (loaded) with Python's pickle module. Feature maps were generated by 
  passing preprocessed microscopy images through the pre-trained Resnet50 
  model.
  '''
 
  # Load saved models
  with open('resources/rf_regressor.mdl', 'rb') as rf_rfile:
    rf_regressor = pickle.load(rf_rfile)
  with open('resources/mlp_regressor.mdl', 'rb') as mlp_rfile:
    mlp_regressor = pickle.load(mlp_rfile)
  with open('resources/ridge_regressor.mdl', 'rb') as ridge_rfile:
    ridge_regressor = pickle.load(ridge_rfile)

  # Load saved feature maps
  with open('resources/feature_maps.pkl','rb') as ftr_rfile:
    feature_maps = pickle.load(ftr_rfile)
  # Select one image to test
  test_feature_map = feature_maps[0].reshape(1,-1)

  print("---------------------------------------------------------")
  print("Saved regressor model predictions for a test feature map:")
  print("Random Forest         :",rf_regressor.predict(test_feature_map))
  print("Multi-Layer Perceptron:",mlp_regressor.predict(test_feature_map))
  print("Ridge                 :",ridge_regressor.predict(test_feature_map))

  return

if __name__ == "__main__":
  main()
